channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal =5.2.4
  - sra-tools =2.11.0
  - pigz =2.6
  - fastp =0.23.2
  - megahit =1.2.9
  - bwa-mem2 =2.2.1
  - samtools =1.15
  - freebayes =1.3.2
  - vcftools =0.1.16
  - scipy =1.5.3
  - r-rstan =2.17
  - busco =5.3.1
